CrossSection:
  NormalisingFunction:
    center: 1.0
    name: left_right_exponential
    spread: 1.0
  compare_with_additional_topologies: false
  do_rescaling: true
  fixed_cut_momenta: []
  gs: 1.2177157847767195
  incoming_momenta:
  - - 500.0
    - 0.0
    - 0.0
    - 500.0
  - - 500.0
    - 0.0
    - 0.0
    - -500.0
  inherit_deformation_for_uv_counterterm: true
  integrand_type: PF
  m_uv_sq: 8315.251344
  mu_r_sq: 8315.251344
  picobarns: true
  small_mass_sq: 0.0
  sum_diagram_sets: false
  uv_cutoff_scale_sq: 250000.0
Deformation:
  additive:
    a_ij: 0.01
    a_ijs: []
    mode: exponential
  fixed:
    M_ij: -0.069
    a_ijs: []
    dampen_on_pinch: true
    dampen_on_pinch_after_lambda: true
    delta: 0.3
    include_normal_source: false
    ir_alpha: 1.0
    ir_beta_ellipse: 1.0
    ir_beta_energy: 1.0
    ir_beta_pinch: 1.0
    ir_handling_strategy: none
    ir_interpolation_length: 0.0
    ir_k_com: 0.0
    ir_k_shift: 1.0
    ir_threshold: 1.0e-08
    local: false
    m_ijs: []
    maximize_radius: false
    mode: hyperbolic
    normalisation_of_subspace_components: true
    normalize_per_source: false
    pinch_dampening_alpha: 2.0
    pinch_dampening_k_com: 1.0
    pinch_dampening_k_shift: 0.0
    sigma: 0.0
    source_dampening_factor: -0.0005
    use_heuristic_centers: true
  lambdas: []
  normalize_on_E_surfaces_m: -1.0
  overall_scaling: constant
  overall_scaling_constant: 1.0
  scaling:
    branch_cut_alpha: 1.0
    branch_cut_check: true
    branch_cut_m: -1.0
    expansion_check_strategy: ratio
    expansion_threshold: -0.3
    lambda: 1.0
    pinch_dampening_m: 0.069
    pole_check_strategy: real_solution
    soft_dampening_m: 0.069
    soft_dampening_power: 1.5
    softmin_sigma: 0.0
    source_branch_cut_m: -1.0
    source_branch_cut_multiplier: 0.8
    source_branch_cut_threshold: 0.8
    theta_c: 10.0
    theta_r_in: 10.0
    theta_r_out: 10.0
General:
  absolute_precision: 1.0e+99
  amplitude: ''
  cut_filter: []
  debug: 0
  deformation_strategy: none
  derive_overlap_structure: false
  minimal_precision_for_returning_result: 10.0
  mu_uv_sq_re_im:
  - 10000.0
  - 0
  multi_channeling: false
  multi_channeling_alpha: -1.0
  multi_channeling_channel: null
  numerical_threshold: 0.0
  partial_fractioning_multiloop: true
  partial_fractioning_threshold: -1
  python_numerator: null
  res_file_prefix: ''
  stability_checks:
  - accepted_radius_range_in_x_space:
    - 0
    - 1.0
    escalate_for_large_weight_threshold: 0.8
    minimal_precision_to_skip_further_checks: 1000.0
    n_samples: 3
    prec: 16
    relative_precision: 10.0
    use_pf: true
  - accepted_radius_range_in_x_space:
    - 0
    - 1.0
    escalate_for_large_weight_threshold: 0.8
    minimal_precision_to_skip_further_checks: 1000.0
    n_samples: 3
    prec: 32
    relative_precision: 8.0
    use_pf: true
  - accepted_radius_range_in_x_space:
    - 0
    - 1.0
    escalate_for_large_weight_threshold: -1.0
    minimal_precision_to_skip_further_checks: 1000.0
    n_samples: 3
    prec: 1000
    relative_precision: 8.0
    use_pf: true
  stability_nudge_size: 0.0
  topology: Box
  use_collinear_ct: false
  use_ct: false
  use_lmb_channels: false
  use_optimal_channels: true
Integrator:
  border: 0.001
  dashboard: true
  eps_abs: 0.0
  eps_rel: 1.0e-08
  flatness: 50.0
  integrated_phase: real
  integrator: vegas
  internal_parallelization: true
  keep_state_file: false
  learning_rate: 1.5
  load_from_state_file: false
  max_discrete_bin_probability_ratio: 100.0
  maxchisq: 0.0
  maxpass: 5
  min_samples_for_update: 1000
  mindeviation: 0.025
  n_bins: 16
  n_increase: 10000
  n_max: 1000000000
  n_min: 2
  n_new: 100000
  n_start: 100000
  n_vec: 5000
  quiet_mode: false
  refine_n_points: 0
  refine_n_runs: 0
  reset_vegas_integrator: true
  seed: 1
  show_plot: false
  state_filename_prefix: ''
  survey_n_iterations: 0
  survey_n_points: 0
  train_on_avg: false
  use_only_last_sample: false
Observables:
- type: cross_section
Parameterization:
  b: 1.0
  input_rescaling:
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  - - - 0.0
      - 1.0
    - - 0.0
      - 1.0
    - - 0.0
      - 1.0
  mapping: linear
  mode: spherical
  shifts:
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
Selectors: []
