ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 MP__G
      COMMON/MP_STRONG/ MP__G

      COMPLEX*32 MP__GAL(2)
      COMMON/MP_WEAK/ MP__GAL

      COMPLEX*32 MP__MU_R
      COMMON/MP_RSCALE/ MP__MU_R


      REAL*16 MP__MDL_MPSIUV,MP__MDL_MT,MP__MDL_MW,MP__MDL_MTA
     $ ,MP__MDL_MZ,MP__MDL_MPSIS,MP__MDL_MH,MP__MDL_MB

      COMMON/MP_MASSES/ MP__MDL_MPSIUV,MP__MDL_MT,MP__MDL_MW
     $ ,MP__MDL_MTA,MP__MDL_MZ,MP__MDL_MPSIS,MP__MDL_MH,MP__MDL_MB


      COMPLEX*32 MP__GC_GH,MP__GC_10,MP__GC_11,MP__GC_12,MP__GC_1
     $ ,MP__GC_2,MP__GC_3,MP__GC_5,MP__GC_6,MP__GC_7,MP__GC_8
     $ ,MP__GC_15,MP__GC_21,MP__GC_31,MP__GC_32,MP__GC_33,MP__GC_34
     $ ,MP__GC_35,MP__GC_36,MP__GC_37,MP__GC_38,MP__GC_50,MP__GC_52
     $ ,MP__GC_54,MP__GC_55,MP__GC_57,MP__GC_58,MP__GC_59,MP__GC_60
     $ ,MP__GC_61,MP__GC_62,MP__GC_63,MP__GC_64,MP__GC_65,MP__GC_66
     $ ,MP__GC_68,MP__GC_69,MP__GC_70,MP__GC_71,MP__GC_72,MP__GC_74
     $ ,MP__GC_76,MP__GC_77,MP__GC_80,MP__GC_81,MP__GC_82,MP__GC_83
     $ ,MP__GC_94,MP__GC_95,MP__GC_96,MP__GC_98,MP__GC_99,MP__GC_100

      COMMON/MP_COUPLINGS/ MP__GC_GH,MP__GC_10,MP__GC_11,MP__GC_12
     $ ,MP__GC_1,MP__GC_2,MP__GC_3,MP__GC_5,MP__GC_6,MP__GC_7,MP__GC_8
     $ ,MP__GC_15,MP__GC_21,MP__GC_31,MP__GC_32,MP__GC_33,MP__GC_34
     $ ,MP__GC_35,MP__GC_36,MP__GC_37,MP__GC_38,MP__GC_50,MP__GC_52
     $ ,MP__GC_54,MP__GC_55,MP__GC_57,MP__GC_58,MP__GC_59,MP__GC_60
     $ ,MP__GC_61,MP__GC_62,MP__GC_63,MP__GC_64,MP__GC_65,MP__GC_66
     $ ,MP__GC_68,MP__GC_69,MP__GC_70,MP__GC_71,MP__GC_72,MP__GC_74
     $ ,MP__GC_76,MP__GC_77,MP__GC_80,MP__GC_81,MP__GC_82,MP__GC_83
     $ ,MP__GC_94,MP__GC_95,MP__GC_96,MP__GC_98,MP__GC_99,MP__GC_100


