ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 G
      COMMON/MP_STRONG/ G

      COMPLEX*32 GAL(2)
      COMMON/MP_WEAK/ GAL

      COMPLEX*32 MU_R
      COMMON/MP_RSCALE/ MU_R


      REAL*16 MDL_MPSIUV,MDL_MT,MDL_MW,MDL_MTA,MDL_MZ,MDL_MPSIS,MDL_MH
     $ ,MDL_MB

      COMMON/MP_MASSES/ MDL_MPSIUV,MDL_MT,MDL_MW,MDL_MTA,MDL_MZ
     $ ,MDL_MPSIS,MDL_MH,MDL_MB


      COMPLEX*32 GC_GH,GC_10,GC_11,GC_12,GC_1,GC_2,GC_3,GC_5,GC_6,GC_7
     $ ,GC_8,GC_15,GC_21,GC_31,GC_32,GC_33,GC_34,GC_35,GC_36,GC_37
     $ ,GC_38,GC_50,GC_52,GC_54,GC_55,GC_57,GC_58,GC_59,GC_60,GC_61
     $ ,GC_62,GC_63,GC_64,GC_65,GC_66,GC_68,GC_69,GC_70,GC_71,GC_72
     $ ,GC_74,GC_76,GC_77,GC_80,GC_81,GC_82,GC_83,GC_94,GC_95,GC_96
     $ ,GC_98,GC_99,GC_100

      COMMON/MP_COUPLINGS/ GC_GH,GC_10,GC_11,GC_12,GC_1,GC_2,GC_3,GC_5
     $ ,GC_6,GC_7,GC_8,GC_15,GC_21,GC_31,GC_32,GC_33,GC_34,GC_35,GC_36
     $ ,GC_37,GC_38,GC_50,GC_52,GC_54,GC_55,GC_57,GC_58,GC_59,GC_60
     $ ,GC_61,GC_62,GC_63,GC_64,GC_65,GC_66,GC_68,GC_69,GC_70,GC_71
     $ ,GC_72,GC_74,GC_76,GC_77,GC_80,GC_81,GC_82,GC_83,GC_94,GC_95
     $ ,GC_96,GC_98,GC_99,GC_100


