      SUBROUTINE DLUM_1(LUM)
C     ****************************************************            
C         
C     Generated by MadGraph5_aMC@NLO v. 3.6.1, 2024-11-29
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     RETURNS PARTON LUMINOSITIES FOR MADFKS                          
C        
C     
C     Process: a a > c c~ g [ all = QCD QED ] QCD^2=2 QED^2=6
C     
C     ****************************************************            
C         
      IMPLICIT NONE
C     
C     CONSTANTS                                                       
C         
C     
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379660D0)  !CONV TO PICOBARNS             
C     
C     ARGUMENTS                                                       
C         
C     
      DOUBLE PRECISION LUM
C     
C     LOCAL VARIABLES                                                 
C         
C     
      INTEGER I, ICROSS,LP
      DOUBLE PRECISION A1
      DOUBLE PRECISION A2
C     
C     STUFF FOR UPC
C     
      DOUBLE PRECISION PHOTONPDFSQUARE
C     
C     EXTERNAL FUNCTIONS                                              
C         
C     
      DOUBLE PRECISION PDG2PDF
C     HSS DEBUG
      DOUBLE PRECISION epa_electron
C     
C     GLOBAL VARIABLES                                                
C         
C     
      INTEGER              IPROC
      DOUBLE PRECISION PD(0:MAXPROC)
      COMMON /SUBPROC/ PD, IPROC
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
      INTEGER IMIRROR
      COMMON/CMIRROR/IMIRROR
C     
C     STUFF FOR DRESSED EE COLLISIONS
C     
      INCLUDE 'eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD
      DOUBLE PRECISION DUMMY_COMPONENTS(N_EE)
      DOUBLE PRECISION A1_COMPONENTS(N_EE)
      DOUBLE PRECISION A2_COMPONENTS(N_EE)

      INTEGER I_EE
      INCLUDE '../../Source/PDF/pdf.inc'
C     
C     DATA                                                            
C         
C     
      DATA A1/1*1D0/
      DATA A2/1*1D0/
      DATA ICROSS/1/
C     ----------                                                      
C         
C     BEGIN CODE                                                      
C         
C     ----------                                                      
C         
      LUM = 0D0
      IF (ABS(LPP(1)).EQ.2.AND.ABS(LPP(2)).EQ.2.AND.(PDLABEL(1:4)
     $ .EQ.'edff'.OR.PDLABEL(1:4).EQ.'chff'))THEN
C        A1=PHOTONPDFSQUARE(XBK(1),XBK(2))
C        A2=DSQRT(A1)
C        A1=A2
c     HSS DEBUG (for electron beam)
c     we take q2max=1d0
        A1=epa_electron(XBK(1),1d0)
        A2=epa_electron(XBK(2),1d0)
      ELSE
        IF (ABS(LPP(1)) .GE. 1) THEN
          A1=PDG2PDF(LPP(1),7,1,XBK(1),DSQRT(Q2FACT(1)))
          IF ((ABS(LPP(1)).EQ.4.OR.ABS(LPP(1)).EQ.3)
     $     .AND.PDLABEL.NE.'none') A1_COMPONENTS(1:N_EE) =
     $      EE_COMPONENTS(1:N_EE)
        ENDIF
        IF (ABS(LPP(2)) .GE. 1) THEN
          A2=PDG2PDF(LPP(2),7,2,XBK(2),DSQRT(Q2FACT(2)))
          IF ((ABS(LPP(2)).EQ.4.OR.ABS(LPP(2)).EQ.3)
     $     .AND.PDLABEL.NE.'none') A2_COMPONENTS(1:N_EE) =
     $      EE_COMPONENTS(1:N_EE)
        ENDIF
      ENDIF
      PD(0) = 0D0
      IPROC = 0
      IPROC=IPROC+1  ! a a > c c~ g
      PD(IPROC) = A1*A2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND. (ABS(LPP(1))
     $ .EQ.3.OR.ABS(LPP(1)).EQ.4).AND.PDLABEL.NE.'none')PD(IPROC)
     $ =EE_COMP_PROD(A1_COMPONENTS,A2_COMPONENTS)
      DO I=1,IPROC
        IF (NINCOMING.EQ.2) THEN
          LUM = LUM + PD(I) * CONV
        ELSE
          LUM = LUM + PD(I)
        ENDIF
      ENDDO
      RETURN
      END

