ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of aL_sm-no_widths_massless_scalar'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_GH = ', GC_GH
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_15 = ', GC_15
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_31 = ', GC_31
      WRITE(*,2) 'GC_32 = ', GC_32
      WRITE(*,2) 'GC_33 = ', GC_33
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_52 = ', GC_52
      WRITE(*,2) 'GC_54 = ', GC_54
      WRITE(*,2) 'GC_55 = ', GC_55
      WRITE(*,2) 'GC_57 = ', GC_57
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_59 = ', GC_59
      WRITE(*,2) 'GC_60 = ', GC_60
      WRITE(*,2) 'GC_61 = ', GC_61
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_63 = ', GC_63
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_65 = ', GC_65
      WRITE(*,2) 'GC_66 = ', GC_66
      WRITE(*,2) 'GC_68 = ', GC_68
      WRITE(*,2) 'GC_69 = ', GC_69
      WRITE(*,2) 'GC_70 = ', GC_70
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_74 = ', GC_74
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_82 = ', GC_82
      WRITE(*,2) 'GC_83 = ', GC_83
      WRITE(*,2) 'GC_94 = ', GC_94
      WRITE(*,2) 'GC_95 = ', GC_95
      WRITE(*,2) 'GC_96 = ', GC_96
      WRITE(*,2) 'GC_98 = ', GC_98
      WRITE(*,2) 'GC_99 = ', GC_99
      WRITE(*,2) 'GC_100 = ', GC_100
